### ISSUE TITLE
Umbrella issues for crictl

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-tools#26]
Umbrella issues for crictl, the CLI for kubelet CRI.

**global options**

```
--debug
--help
--timeout
--runtime-endpoint
--image-endpoint
```

**Sub commands**

- [x] version
- [x] status
- [x] sandbox #40 
  - [x] sandbox run config.json|yaml
  - [x] sandbox status sandbox-id
  - [x] sandbox stop sandbox-id
  - [x] sandbox remove sandbox-id
  - [x] sandbox list
- [x] container
  - [x] container create sandbox-id config.json|yaml
  - [x] container start container-id
  - [x] container stop container-id
  - [x] container remove container-id
  - [x] container status container-id
  - [x] container list
- [x] image
  - [x] image list
  - [x] image pull [--auth ] NAME[:TAG|@DIGEST]
  - [x] image remove NAME[:TAG|@DIGEST]
  - [x] image status NAME[:TAG|@DIGEST]
- [x] exec [--sync]
- [x] attach
- [x] portforward

cc/ @mrunalp @yujuhong @Random-Liu @xlgao-zju Any comments on the crictl?

**Comment by xlgao-zju** [comment]
Should also support `sandbox/container remove config.json|yaml` form?

**Comment by feiskyer** [comment]
> Should also support sandbox/container remove config.json|yaml form?

I don't think so. We only pass the id of sandbox/container in removal API.

**Comment by xlgao-zju** [comment]
What will `--debug` do? Print the response of shim or something like that?

**Comment by feiskyer** [comment]
yes, `--debug` prints the raw string of requests and response.

**Comment by mrunalp** [comment]
We can give a pod-id arg to container create, right?

**Comment by feiskyer** [comment]
> We can give a pod-id arg to container create, right?

Yes, of course. 

@mrunalp Could you help to move `ocic` from cri-o to here for a starting point of crictl?

**Comment by mrunalp** [comment]
@feiskyer Yes, I will have a PR ready in a day or two.

**Comment by feiskyer** [comment]
@mrunalp Cool 👍

**Comment by feiskyer** [comment]
Note: splited tasks into separate small issues. Please claim works there.

**Comment by xlgao-zju** [comment]
@heartlock As @feiskyer said [here](https://github.com/kubernetes-incubator/cri-tools/issues/26#issuecomment-287676901). We should add `--debug` flag in order to print the responses and the requests.
