### ISSUE TITLE
Umbrella issues for validation tests

### ISSUE THREAD

**Issue by xlgao-zju** [kubernetes-incubator/cri-tools#4]
Here is the list of functionality test, based on https://github.com/kubernetes-incubator/cri-tools/issues/4#issue-209695062 and https://github.com/kubernetes-incubator/cri-tools/issues/4#issuecomment-282947338:
- [x] P0 Basic (Conformance):
  - [x] sandbox: run/stop/remove/list/status #8 
  - [x] container: create/start/execSync/remove/status #13 
  - [x] image: pull/list/status/remove #9 
  - [x] version #8 
  - [x] status #11 
  - [x] logs @Helen-Xie #28 
  - [x] networking: DNSOptions/PortMapping/IP @xlgao-zju #30 
  - [x] volumes #27 
- [x] P0 SecurityContext (only subset of this function are testable): 
  - [x] container with security context:
    - [x] NamespaceOption
      - [x] hostPID #56 
      - [x] hostIPC #82 
      - [x] hostNetwork #75 
    - [x] Priviledged #78 
    - [x] Capabilities #80 
    - [x] RunAsUser/RunAsUserName #41 
    - [x] ReadOnlyRootfs #53 
- [x] P1 Streaming (Conformance): 
  - [x] exec #58 
  - [x] attach #64 
  - [x] portfoward #71 
- [ ] P2 Resource Limits
- [ ] P2 updateRuntimeConfig
- [ ] P2 Experimental: apparmor/sysctls/seccomp
- [ ] P2 Devices
- [ ] P2 SELinuxOption

See [more details](https://docs.google.com/document/d/1usdMWxOXvKIQ00UPRYQWNKY4jeL66FpbHnL7dz0m6qc/edit?usp=sharing) about each test.

The list may not be sufficient enough. Please feel free to:
* Point out anything is missing or incorrect.
* Claim any test you'd like to help.

/cc @feiskyer @resouer @xlgao-zju @Helen-Xie @yujuhong @dchen1107 @mrunalp @lucab

**Comment by resouer** [comment]
Move discussion to https://github.com/kubernetes-incubator/cri-tools/pull/6

**Comment by xlgao-zju** [comment]
@resouer Yes, will keep this issue only for tracking PRs about test case.

**Comment by Random-Liu** [comment]
@feiskyer @resouer @xlgao-zju @Helen-Xie
Here is a document for the CRI function validation test:
https://docs.google.com/document/d/1usdMWxOXvKIQ00UPRYQWNKY4jeL66FpbHnL7dz0m6qc/edit?usp=sharing

Feel free to comment if you have any ideas.

**Comment by feiskyer** [comment]
@Random-Liu Made an update on the docs. PTAL.

**Comment by Random-Liu** [comment]
@feiskyer Thanks! Commented on your comment. :)

Also /cc @mrunalp @lucab who are working on other runtime integration.

**Comment by resouer** [comment]
There's not performance test plan. Although there's already Docker micro benchmark, we still need to a detailed doc like this (thanks landao and feiskyer's work) @xlgao-zju @Helen-Xie

**Comment by Random-Liu** [comment]
@resouer Thanks! Will wait for your update! :)

**Comment by Random-Liu** [comment]
Based on https://github.com/kubernetes-incubator/cri-tools/issues/4#issue-209695062 and https://github.com/kubernetes-incubator/cri-tools/issues/4#issuecomment-282947338, here is the list of functionality test:
- [ ] P0 Basic (Conformance):
  - [ ] sandbox: run/stop/remove/list/status
  - [ ] container: create/start/execSync/remove/status
  - [ ] image: pull/list/status/remove
  - [ ] version
  - [ ] status
  - [ ] logs
  - [ ] networking: DNSOptions/PortMapping/IP
  - [ ] volumes/devices
- [ ] P0 SecurityContext (only subset of this function are testable): 
  - [ ] sandbox with security context: 
    - [ ] NamespaceOption
  - [ ] container with security context:
    - [ ] NamespaceOption
    - [ ] Priviledged
    - [ ] Capabilities
    - [ ] SELinuxOption
    - [ ] RunAsUser/RunAsUserName
    - [ ] ReadOnlyRootfs
- [ ] P1 Streaming (Conformance): 
  - [ ] exec
  - [ ] attach
  - [ ] portfoward
- [ ] P2 Resource Limits
- [ ] P2 updateRuntimeConfig
- [ ] P2 Experimental: apparmor/sysctls/seccomp

See [more details](https://docs.google.com/document/d/1usdMWxOXvKIQ00UPRYQWNKY4jeL66FpbHnL7dz0m6qc/edit?usp=sharing) about each test.

The list may not be sufficient enough. Please feel free to:
* Point out anything is missing.
* Claim any test you'd like to help.


/cc @feiskyer @resouer @xlgao-zju @Helen-Xie @yujuhong @dchen1107@mrunalp @lucab

**Comment by Random-Liu** [comment]
Removed checkbox in https://github.com/kubernetes-incubator/cri-tools/issues/4#issuecomment-283837387 in favor of https://github.com/kubernetes-incubator/cri-tools/issues/4#issue-209695062. :)

**Comment by xlgao-zju** [comment]
Should we put version test case and status test case into one file called `pkg/validate/runtime_info.go` or something?

cc @feiskyer @Random-Liu

**Comment by feiskyer** [comment]
All P0 and P1 cases have been done. And thanks to @xlgao-zju @heartlock @Helen-Xie.

**Comment by xlgao-zju** [comment]
:tada: Also thanks @feiskyer for your reviewing and ideas about the cases.

**Comment by feiskyer** [comment]
All remaining P2 items have been in their separate issues, closing this one.
